// ignore_for_file: file_names

List<Map<String, dynamic>> universeMock = [
  {
    "id": 1,
    "MoviewName": "Captain America: The First Avenger",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "captain america.jpg",
    "ReleaseDate": "2011",
    "YoutubeId": "jF1IHPba2Bk",
    "music": "captain_america_the_first_avenger.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 2,
    "MoviewName": "Agent Carter",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "agent carter.jpg",
    "ReleaseDate": "2015",
    "YoutubeId": "jtDrUCL64NM",
    "music": "agent_carter.mp3",
    "niveau": "intéressant",
  },
  {
    "id": 3,
    "MoviewName": "Captain Marvel",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "captain_marvel_1.jpg",
    "YoutubeId": "rndLWLmwgeA",
    "ReleaseDate": "2019",
    "music": "captain_marvel_1.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 4,
    "MoviewName": "Iron Man",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 6min",
    "Thumbnail": "iron man.jpg",
    "YoutubeId": "rDCTb9Gp2qk",
    "ReleaseDate": "2008",
    "music": "iron_man.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 5,
    "MoviewName": "Iron Man 2",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "iron man 2.jpg",
    "YoutubeId": "SQnuLDnhB7g",
    "ReleaseDate": "2010",
    "music": "iron_man_2.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 6,
    "MoviewName": "Hulk",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 52min",
    "Thumbnail": "hulk.png",
    "YoutubeId": "LCjTxK1B5Pg",
    "ReleaseDate": "2008",
    "music": "hulk.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 7,
    "MoviewName": "Le consultant",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "4min",
    "Thumbnail": "consultant.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2011",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 8,
    "MoviewName": "Une drôle d'histoire sur la route du marteau",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "4min",
    "Thumbnail": "marteau.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2011",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 9,
    "MoviewName": "Thor",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 55min",
    "ReleaseDate": "2011",
    "Thumbnail": "thor.png",
    "YoutubeId": "pzT3yeV9lT4",
    "music": "thor.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 10,
    "MoviewName": "Avengers",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 23min",
    "Thumbnail": "avengers.jpg",
    "YoutubeId": "b-kTeJhHOhc",
    "ReleaseDate": "2012",
    "music": "avengers.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 11,
    "MoviewName": "Item 47",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "12min",
    "Thumbnail": "item.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2012",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 12,
    "MoviewName": "Les Agents du SHIELD",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "agent.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2013",
    "music": "agent.mp3",
    "niveau": "interessant",
  },
  {
    "id": 13,
    "MoviewName": "Thor: Le monde des ténèbres",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 52min",
    "Thumbnail": "thor dark.jpg",
    "YoutubeId": "JXmOod9zBME",
    "ReleaseDate": "2013",
    "music": "thor_the_dark_world.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 14,
    "MoviewName": "Iron Man 3",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 10min",
    "Thumbnail": "iron man 3.jpg",
    "YoutubeId": "wnEr73Rq3Ac",
    "ReleaseDate": "2013",
    "music": "iron_man_3.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 15,
    "MoviewName": "All Hail the King",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "14min",
    "Thumbnail": "king.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2013",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 16,
    "MoviewName": "Captain America: Le soldat de l'hiver",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 16min",
    "Thumbnail": "captain 2.jpg",
    "YoutubeId": "6mQWmUwxZjI",
    "ReleaseDate": "2014",
    "music": "captain_america_the_winter_soldier.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 17,
    "MoviewName": "Les Gardiens de la Galaxie",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 2min",
    "Thumbnail": "gardiens 1.jpg",
    "YoutubeId": "HbB1LC_QyK0",
    "ReleaseDate": "2014",
    "music": "guardians_of_the_galaxy.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 18,
    "MoviewName": "Les Gardiens de la Galaxie Vol. 2",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 17min",
    "Thumbnail": "gardiens 2.jpg",
    "YoutubeId": "qe6EjVKba9Q",
    "ReleaseDate": "2017",
    "music": "guardians_of_the_galaxy_2.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 19,
    "MoviewName": "I am Groot",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "groot.jpg",
    "YoutubeId": "D7eFpRf4tac",
    "ReleaseDate": "2022",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 20,
    "MoviewName": "Dardevil",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "3 saisons",
    "Thumbnail": "dardevil.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2015",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 21,
    "MoviewName": "Jessica Jones",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "3 saisons",
    "Thumbnail": "jessica.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2015",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 22,
    "MoviewName": "Avengers: L'ère d'Ultron",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 21min",
    "Thumbnail": "avengers 2.jpg",
    "YoutubeId": "ANbZ-zJ7Ig8",
    "ReleaseDate": "2015",
    "music": "avengers_age_of_ultron.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 23,
    "MoviewName": "Ant Man",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 58min",
    "Thumbnail": "ant man.jpg",
    "YoutubeId": "_mWjqYXA59E",
    "ReleaseDate": "2015",
    "music": "ant_man.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 24,
    "MoviewName": "Luke Cage",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "luke.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2016",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 25,
    "MoviewName": "Iron Fist",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "iron.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2017",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 26,
    "MoviewName": "Defenders",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "1 saison",
    "Thumbnail": "defenders.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2017",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 27,
    "MoviewName": "Captain America: Civil War",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 28min",
    "Thumbnail": "civil war.jpg",
    "YoutubeId": "fuIIGDjEj8Q",
    "ReleaseDate": "2015",
    "music": "captain_america_civil_war.mp3",
    "niveau": "immanquable",
  },

  {
    "id": 28,
    "MoviewName": "Black Widow",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 14min",
    "Thumbnail": "black_widow.jpg",
    "YoutubeId": "4l99M0zOEaA",
    "ReleaseDate": "2021",
    "music": "black_widow.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 29,
    "MoviewName": "Eyes of Wakanda",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "1 saison",
    "Thumbnail": "eyes.jpg",
    "YoutubeId": "3ch9VVrLqG0",
    "ReleaseDate": "2025",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 30,
    "MoviewName": "Black Panther",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 15min",
    "Thumbnail": "black_panther.jpg",
    "YoutubeId": "8RQpN5kQslw",
    "ReleaseDate": "2018",
    "music": "black_panther.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 31,
    "MoviewName": "Spiderman: Homecoming",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 13min",
    "Thumbnail": "spiderman_1.jpg",
    "YoutubeId": "Y8ErdqD5YPc",
    "ReleaseDate": "2017",
    "music": "spiderman_1.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 32,
    "MoviewName": "The Punisher",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2 saisons",
    "Thumbnail": "punisher.jpg",
    "YoutubeId": "09Gz82tLmXA",
    "ReleaseDate": "2017",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 33,
    "MoviewName": "Doctor Strange",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 55min",
    "Thumbnail": "doctor_strange_1.jpg",
    "YoutubeId": "r849NGQZqbA",
    "ReleaseDate": "2016",
    "music": "doctor_strange_1.mp3",
    "niveau": "immanquable",
  },

  {
    "id": 34,
    "MoviewName": "Thor: Ragnarok",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 10min",
    "Thumbnail": "thor_ragnarok.jpg",
    "YoutubeId": "RtG6scyBIeM",
    "ReleaseDate": "2017",
    "music": "thor_ragnarok.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 35,
    "MoviewName": "Avengers: Infinity War",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 24min",
    "Thumbnail": "avengers_infinity_war.jpg",
    "YoutubeId": "DjYBTqgj8uE",
    "ReleaseDate": "2018",
    "music": "avengers_infinity_war.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 36,
    "MoviewName": "Ant-Man et la Guêpe",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 58min",
    "Thumbnail": "ant_man_guepe.png",
    "YoutubeId": "A5jzpMR6rv4",
    "ReleaseDate": "2018",
    "music": "ant_man_guepe.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 37,
    "MoviewName": "Avengers: Endgame",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "3h 1min",
    "Thumbnail": "avengers_endgame.png",
    "YoutubeId": "wV-Q0o2OQjQ",
    "ReleaseDate": "2019",
    "music": "avengers_endgame.mp3",
    "niveau": "immanquable",
  },
  // ****************************** MULTIVERS ****************************************************
  {
    "id": 38,
    "MoviewName": "Loki",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2 saisons",
    "Thumbnail": "loki_saison.jpg",
    "YoutubeId": "iYpS70gCsvw",
    "ReleaseDate": "2022",
    "music": "loki.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 39,
    "MoviewName": "WandaVision",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "wandaVision.jpg",
    "YoutubeId": "bQCvUqWqivY",
    "ReleaseDate": "2021",
    "music": "wandaVision.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 40,
    "MoviewName": "What If...?",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "3 saison",
    "Thumbnail": "what.jpg",
    "YoutubeId": "NDfaxdYx34Y",
    "ReleaseDate": "2021",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 41,
    "MoviewName": "Falcon et le Soldat de l'hiver",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "falcon.jpg",
    "YoutubeId": "X_mSpyPVVzk",
    "ReleaseDate": "2021",
    "music": "falcon.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 42,
    "MoviewName": "Shang-Chi et la Légende des dix Anneaux",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 12min",
    "Thumbnail": "shang.jpg",
    "YoutubeId": "PD3rUCBFDlI",
    "ReleaseDate": "2021",
    "music": "shang.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 43,
    "MoviewName": "Les Eternels",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 37min",
    "Thumbnail": "eternals.jpg",
    "YoutubeId": "nHcubNwuKFA",
    "ReleaseDate": "2021",
    "music": "eternals.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 44,
    "MoviewName": "Spiderman: Far From Home",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 10min",
    "Thumbnail": "spiderman2.jpg",
    "YoutubeId": "FguIk-SEkWI",
    "ReleaseDate": "2019",
    "music": "spiderman2.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 45,
    "MoviewName": "Ancients Spiderman",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "5 films",
    "Thumbnail": "ancient.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2002-2014",
    "music": "ancient.mp3",
    "niveau": "interessant",
  },
  {
    "id": 46,
    "MoviewName": "Venom",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2 films",
    "Thumbnail": "venom.jpg",
    "YoutubeId": "Pw9ZvTicmIg",
    "ReleaseDate": "2018-2021",
    "music": "venom.mp3",
    "niveau": "optionnel",
  },
  {
    "id": 47,
    "MoviewName": "Spiderman: No Way Home",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 30min",
    "Thumbnail": "spiderman3.jpg",
    "YoutubeId": "7w_w10HVa54",
    "ReleaseDate": "2021",
    "music": "spiderman3.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 48,
    "MoviewName": "Doctor Strange in the Multiverse of Madness",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 6min",
    "Thumbnail": "doctor_strange_2.jpg",
    "YoutubeId": "J7u1bDo_4sk",
    "ReleaseDate": "2022",
    "music": "doctor_strange_2.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 49,
    "MoviewName": "Hawkeye",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "hawkeye.jpg",
    "YoutubeId": "P-6jVdKj_dk",
    "ReleaseDate": "2021",
    "music": "hawkeye.mp3",
    "niveau": "interessant",
  },
  {
    "id": 50,
    "MoviewName": "Moon Knight",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "moon_knight.jpg",
    "YoutubeId": "NZnxfCArhY8",
    "ReleaseDate": "2022",
    "music": "moon_knight.mp3",
    "niveau": "interessant",
  },
  {
    "id": 51,
    "MoviewName": "Black Panther: Wakanda Forever",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 41min",
    "Thumbnail": "black_panther_wakanda_forever.jpg",
    "YoutubeId": "DlGIWM_e9vg",
    "ReleaseDate": "2022",
    "music": "black_panther_wakanda_forever.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 52,
    "MoviewName": "Echo",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2 saisons",
    "Thumbnail": "echo.jpg",
    "YoutubeId": "aZtwmbk1HkA",
    "ReleaseDate": "2023",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 53,
    "MoviewName": "She Hulk : Avocate",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "she_hulk.jpg",
    "YoutubeId": "tcqmEgtApbw",
    "ReleaseDate": "2022",
    "music": "she_hulk.mp3",
    "niveau": "optionnel",
  },
  {
    "id": 54,
    "MoviewName": "Ms Marvel",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "ms_marvel.jpg",
    "YoutubeId": "dFNPm6kuOP4",
    "ReleaseDate": "2022",
    "music": "ms_marvel.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 55,
    "MoviewName": "Thor: Love and Thunder",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 13min",
    "Thumbnail": "thor_love_and_thunder.jpg",
    "YoutubeId": "wPPim0we5m8",
    "ReleaseDate": "2022",
    "music": "thor_love_and_thunder.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 56,
    "MoviewName": "Ironheart",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "iron_heart.jpg",
    "YoutubeId": "xsQKZ5RxGTE",
    "ReleaseDate": "2025",
    "music": "iron_heart.mp3",
    "niveau": "interessant",
  },
  {
    "id": 57,
    "MoviewName": "Werewolf by Night",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2h 13min",
    "Thumbnail": "werewolf.jpg",
    "YoutubeId": "kBfA0ig6qSw",
    "ReleaseDate": "2022",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 58,
    "MoviewName": "Les Gardiens de la Galaxie : Joyeuses Fêtes",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "42 min",
    "Thumbnail": "noel.jpg",
    "YoutubeId": "W8YMK0SqEoU",
    "ReleaseDate": "2022",
    "music": "",
    "niveau": "optionnel",
  },
  {
    "id": 59,
    "MoviewName": "Ant-Man et la Guêpe : Quantumania",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "2h 5min",
    "Thumbnail": "ant_man_3.jpg",
    "YoutubeId": "Q0uaHT1wsTQ",
    "ReleaseDate": "2023",
    "music": "ant_man_3.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 60,
    "MoviewName": "Les Gardiens de la Galaxie Vol. 3",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "2h 29min",
    "Thumbnail": "gardien_3.jpg",
    "YoutubeId": "WxA-eZ72FsQ",
    "ReleaseDate": "2023  ",
    "music": "gardien_3.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 61,
    "MoviewName": "Secret Invasion",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "secret_invasion.jpg",
    "YoutubeId": "CYzBmMbC2wk",
    "ReleaseDate": "2023  ",
    "music": "secret_invasion.mp3",
    "niveau": "optionnel",
  },
  {
    "id": 62,
    "MoviewName": "The Marvels",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "1h 45min",
    "Thumbnail": "the_marvels.jpg",
    "YoutubeId": "9z9_bfhpLzU",
    "ReleaseDate": "2023",
    "music": "the_marvels.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 63,
    "MoviewName": "Agatha All Along",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "agatha.jpg",
    "YoutubeId": "2BboKBmO8uI",
    "ReleaseDate": "2024",
    "music": "agatha.mp3",
    "niveau": "interessant",
  },
  {
    "id": 64,
    "MoviewName": "Daredevil: Born Again",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "1 saison",
    "Thumbnail": "dardevill.jpg",
    "YoutubeId": "mdEqcqglkDE",
    "ReleaseDate": "2025",
    "music": "dardevill.mp3",
    "niveau": "interessant",
  },
  {
    "id": 65,
    "MoviewName": "Captain America: Brave New World",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "1h 58min",
    "Thumbnail": "captain_4.jpg",
    "YoutubeId": "MOwkseguLXQ",
    "ReleaseDate": "2025",
    "music": "captain_4.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 66,
    "MoviewName": "Thunderbolts*",
    "Phase": "Phase 5",
    "Saga": "Saga du multivers",
    "RunTime": "2h 6min",
    "Thumbnail": "Thunderbolts.jpg",
    "YoutubeId": "cYHyGlHIOOY",
    "ReleaseDate": "2025",
    "music": "Thunderbolts.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 67,
    "MoviewName": "Ancients 4 Fantastiques",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "3 films",
    "Thumbnail": "4FF.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2005-2015",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 68,
    "MoviewName": "Les 4 Fantastiques: Premiers Pas",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "1h 55min",
    "Thumbnail": "fantastique.jpg",
    "YoutubeId": "sdPlkUZE98I",
    "ReleaseDate": "2025",
    "music": "fantastique.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 69,
    "MoviewName": "Logan",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "2h 17min",
    "Thumbnail": "logan.jpg",
    "YoutubeId": "i-iqiI5uikE",
    "ReleaseDate": "2017",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 70,
    "MoviewName": "Logan",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "2 films",
    "Thumbnail": "deadpool_movie.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2016-2018",
    "music": "",
    "niveau": "interessant",
  },
  {
    "id": 71,
    "MoviewName": "Deadpool & Wolverine",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "1h 45min",
    "Thumbnail": "deadpool.jpg",
    "YoutubeId": "2t9-VpzzNm",
    "ReleaseDate": "2024",
    "music": "deadpool.mp3",
    "niveau": "immanquable",
  },
  {
    "id": 72,
    "MoviewName": "Spider-Man: Brand New Day",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "",
    "Thumbnail": "spiderman_4.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2026",
    "music": "",
    "niveau": "immanquable",
  },
  {
    "id": 73,
    "MoviewName": "Avengers: DoomsDay",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "",
    "Thumbnail": "avengers_5.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2026",
    "music": "",
    "niveau": "immanquable",
  },
  {
    "id": 74,
    "MoviewName": "Avengers: Secret Wars",
    "Phase": "Phase 6",
    "Saga": "Saga du multivers",
    "RunTime": "",
    "Thumbnail": "avengers_6.jpg",
    "YoutubeId": "",
    "ReleaseDate": "2027",
    "music": "",
    "niveau": "immanquable",
  },
];
