// ignore_for_file: file_names

List<Map<String, dynamic>> universeMock = [
  {
    "id": 1,
    "MoviewName": "Iron Man",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 6min",
    "Thumbnail": "iron man.jpg",
    "YoutubeId": "rDCTb9Gp2qk",
    "ReleaseDate": "2008",
    "music": "iron_man.mp3",
  },
  {
    "id": 2,
    "MoviewName": "Captain America: The First Avenger",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "captain america.jpg",
    "ReleaseDate": "2011",
    "YoutubeId": "jF1IHPba2Bk",
    "music": "captain_america_the_first_avenger.mp3",
  },
  {
    "id": 3,
    "MoviewName": "Hulk",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 52min",
    "Thumbnail": "hulk.png",
    "YoutubeId": "LCjTxK1B5Pg",
    "ReleaseDate": "2008",
    "music": "hulk.mp3",
  },
  {
    "id": 4,
    "MoviewName": "Iron Man 2",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "iron man 2.jpg",
    "YoutubeId": "SQnuLDnhB7g",
    "ReleaseDate": "2010",
    "music": "iron_man_2.mp3",
  },
  {
    "id": 5,
    "MoviewName": "Thor",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 55min",
    "ReleaseDate": "2011",
    "Thumbnail": "thor.png",
    "YoutubeId": "pzT3yeV9lT4",
    "music": "thor.mp3",
  },
  {
    "id": 6,
    "MoviewName": "Avengers",
    "Phase": "Phase 1",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 23min",
    "Thumbnail": "avengers.jpg",
    "YoutubeId": "b-kTeJhHOhc",
    "ReleaseDate": "2012",
    "music": "avengers.mp3",
  },
  {
    "id": 7,
    "MoviewName": "Thor: Le monde des ténèbres",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 52min",
    "Thumbnail": "thor dark.jpg",
    "YoutubeId": "JXmOod9zBME",
    "ReleaseDate": "2013",
    "music": "thor_the_dark_world.mp3",
  },
  {
    "id": 8,
    "MoviewName": "Iron Man 3",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 10min",
    "Thumbnail": "iron man 3.jpg",
    "YoutubeId": "wnEr73Rq3Ac",
    "ReleaseDate": "2013",
    "music": "iron_man_3.mp3",
  },
  {
    "id": 9,
    "MoviewName": "Captain America: Le soldat de l'hiver",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 16min",
    "Thumbnail": "captain 2.jpg",
    "YoutubeId": "6mQWmUwxZjI",
    "ReleaseDate": "2014",
    "music": "captain_america_the_winter_soldier.mp3",
  },
  {
    "id": 10,
    "MoviewName": "Les Gardiens de la Galaxie",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 2min",
    "Thumbnail": "gardiens 1.jpg",
    "YoutubeId": "HbB1LC_QyK0",
    "ReleaseDate": "2014",
    "music": "guardians_of_the_galaxy.mp3",
  },
  {
    "id": 11,
    "MoviewName": "Avengers: L'ère d'Ultron",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 21min",
    "Thumbnail": "avengers 2.jpg",
    "YoutubeId": "ANbZ-zJ7Ig8",
    "ReleaseDate": "2015",
    "music": "avengers_age_of_ultron.mp3",
  },
  {
    "id": 12,
    "MoviewName": "Ant Man",
    "Phase": "Phase 2",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 58min",
    "Thumbnail": "ant man.jpg",
    "YoutubeId": "_mWjqYXA59E",
    "ReleaseDate": "2015",
    "music": "ant_man.mp3",
  },
  {
    "id": 13,
    "MoviewName": "Captain America: Civil War",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 28min",
    "Thumbnail": "civil war.jpg",
    "YoutubeId": "fuIIGDjEj8Q",
    "ReleaseDate": "2015",
    "music": "captain_america_civil_war.mp3",
  },
  {
    "id": 14,
    "MoviewName": "Les Gardiens de la Galaxie Vol. 2",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 17min",
    "Thumbnail": "gardiens 2.jpg",
    "YoutubeId": "qe6EjVKba9Q",
    "ReleaseDate": "2017",
    "music": "guardians_of_the_galaxy_2.mp3",
  },
  {
    "id": 15,
    "MoviewName": "Black Widow",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 14min",
    "Thumbnail": "black_widow.jpg",
    "YoutubeId": "4l99M0zOEaA",
    "ReleaseDate": "2021",
    "music": "black_widow.mp3",
  },
  {
    "id": 16,
    "MoviewName": "Black Panther",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 15min",
    "Thumbnail": "black_panther.jpg",
    "YoutubeId": "8RQpN5kQslw",
    "ReleaseDate": "2018",
    "music": "black_panther.mp3",
  },
  {
    "id": 17,
    "MoviewName": "Spiderman: Homecoming",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 13min",
    "Thumbnail": "spiderman_1.jpg",
    "YoutubeId": "Y8ErdqD5YPc",
    "ReleaseDate": "2017",
    "music": "spiderman_1.mp3",
  },
  {
    "id": 18,
    "MoviewName": "Doctor Strange",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 55min",
    "Thumbnail": "doctor_strange_1.jpg",
    "YoutubeId": "r849NGQZqbA",
    "ReleaseDate": "2016",
    "music": "doctor_strange_1.mp3",
  },
  {
    "id": 19,
    "MoviewName": "Captain Marvel",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 4min",
    "Thumbnail": "captain_marvel_1.jpg",
    "YoutubeId": "rndLWLmwgeA",
    "ReleaseDate": "2019",
    "music": "captain_marvel_1.mp3",
  },
  {
    "id": 20,
    "MoviewName": "Thor: Ragnarok",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 10min",
    "Thumbnail": "thor_ragnarok.jpg",
    "YoutubeId": "RtG6scyBIeM",
    "ReleaseDate": "2017",
    "music": "thor_ragnarok.mp3",
  },
  {
    "id": 21,
    "MoviewName": "Avengers: Infinity War",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "2h 24min",
    "Thumbnail": "avengers_infinity_war.jpg",
    "YoutubeId": "DjYBTqgj8uE",
    "ReleaseDate": "2018",
    "music": "avengers_infinity_war.mp3",
  },
  {
    "id": 22,
    "MoviewName": "Ant-Man et la Guêpe",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "1h 58min",
    "Thumbnail": "ant_man_guepe.png",
    "YoutubeId": "A5jzpMR6rv4",
    "ReleaseDate": "2018",
    "music": "ant_man_guepe.mp3",
  },
  {
    "id": 23,
    "MoviewName": "Avengers: Endgame",
    "Phase": "Phase 3",
    "Saga": "Saga de l'infini",
    "RunTime": "3h 1min",
    "Thumbnail": "avengers_endgame.png",
    "YoutubeId": "wV-Q0o2OQjQ",
    "ReleaseDate": "2019",
    "music": "avengers_endgame.mp3",
  },
  {
    "id": 24,
    "MoviewName": "Loki",
    "Phase": "Phase 4",
    "Saga": "Saga du multivers",
    "RunTime": "2 saisons",
    "Thumbnail": "loki_saison.jpg",
    "YoutubeId": "iYpS70gCsvw",
    "ReleaseDate": "2022",
    "music": "loki.mp3",
  },
];
